FROM mvn-jdk as builder
ADD . /tmp/spring-framework-petclinic/
WORKDIR /tmp/spring-framework-petclinic/
ENV MVN_COMMAND "-Dmaven.test.skip=true"
RUN mvn $MVN_COMMAND
RUN ls -lah

FROM tomcat as webcontainer
COPY --from=builder /tmp/spring-framework-petclinic/target/petclinic.war /usr/local/tomcat/webapps/petclinic.war
