version: '3'

services:
 jenkins:
   image: jenkins
   container_name: jenkins
   ports:
     - "8080:8080"
     - "50000:50000"
   volumes:
     - "/Users/rodrigosiviero/jenkins_home:/var/jenkins_home"
 db:
   image: postgres
   environment:
     POSTGRES_PASSWORD: sonar123
     POSTGRES_USER: sonar
     POSTGRES_DB: sonar
   volumes:
     - "/Users/rodrigosiviero/postgresql:/var/lib/postgresql/data"
   ports:
     - "5432:5432"
 sonar:
   image: sonarqube
   environment:
     SONARQUBE_JDBC_USERNAME: sonar
     SONARQUBE_JDBC_PASSWORD: sonar123
     SONARQUBE_JDBC_URL: jdbc:postgresql://db/sonar
   depends_on:
     - db
   links:
     - db
   volumes:
     - "/Users/rodrigosiviero/sonarqube/conf:/opt/sonarqube/conf"
     - "/Users/rodrigosiviero/sonarqube/data:/opt/sonarqube/data"
   ports:
     - "9000:9000"
     - "9092:9092"
networks:
  sonarnet:
    driver: bridge
